export const PERMISSIONS = {
  // User Management
  USER_VIEW: 'user.view',
  USER_MANAGE: 'user.manage',
  USER_ASSIGN_ROLE: 'user.assign_role',

  // Departments
  DEPARTMENT_VIEW: 'department.view',
  DEPARTMENT_MANAGE: 'department.manage',

  // Customers
  CUSTOMER_VIEW: 'customer.view',
  CUSTOMER_MANAGE: 'customer.manage',

  // Projects
  PROJECT_VIEW: 'project.view',
  PROJECT_CREATE: 'project.create',
  PROJECT_UPDATE: 'project.update',
  PROJECT_CLOSE: 'project.close',
  PROJECT_REOPEN: 'project.reopen',

  // Tasks
  TASK_VIEW: 'task.view',
  TASK_CREATE: 'task.create',
  TASK_ASSIGN: 'task.assign',
  TASK_APPROVE: 'task.approve',

  // Attendance
  ATTENDANCE_VIEW_OWN: 'attendance.view_own',
  ATTENDANCE_VIEW_DEPARTMENT: 'attendance.view_department',
  ATTENDANCE_VIEW_ALL: 'attendance.view_all',
  ATTENDANCE_MANAGE: 'attendance.manage',

  // Leave Requests
  LEAVE_CREATE: 'leave.create',
  LEAVE_VIEW_OWN: 'leave.view_own',
  LEAVE_APPROVE: 'leave.approve',

  // Salary
  SALARY_VIEW_OWN: 'salary.view_own',
  SALARY_VIEW_ALL: 'salary.view_all',
  SALARY_CREATE: 'salary.create',
  SALARY_UPDATE: 'salary.update',

  // Payroll
  PAYROLL_CREATE: 'payroll.create',
  PAYROLL_SUBMIT: 'payroll.submit',
  PAYROLL_APPROVE: 'payroll.approve',
  PAYROLL_LOCK: 'payroll.lock',
  PAYROLL_PAYMENT_RECORD: 'payroll.payment_record',

  // Deliverables
  DELIVERABLE_VIEW: 'deliverable.view',
  DELIVERABLE_CREATE: 'deliverable.create',
  DELIVERABLE_PUBLISH: 'deliverable.publish',
  DELIVERABLE_APPROVE: 'deliverable.approve',
  DELIVERABLE_REQUEST_CHANGES: 'deliverable.request_changes',

  // Notifications
  NOTIFICATION_VIEW_OWN: 'notification.view_own',
  NOTIFICATION_MANAGE_PREFERENCES: 'notification.manage_preferences',

  // Audit Logs
  AUDIT_VIEW: 'audit.view',

  // System Manage
  SYSTEM_MANAGE: 'system.manage',
} as const;

export type PermissionCode = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const SYSTEM_ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  EMPLOYEE: 'EMPLOYEE',
  ACCOUNTANT: 'ACCOUNTANT',
  CLIENT: 'CLIENT',
} as const;

export type SystemRole = typeof SYSTEM_ROLES[keyof typeof SYSTEM_ROLES];

// Mapped permissions per role (initial config)
export const ROLE_PERMISSIONS_MAPPING: Record<SystemRole, PermissionCode[]> = {
  ADMIN: Object.values(PERMISSIONS), // Admin has all permissions
  MANAGER: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_APPROVE,
    PERMISSIONS.ATTENDANCE_VIEW_OWN,
    PERMISSIONS.ATTENDANCE_VIEW_DEPARTMENT,
    PERMISSIONS.LEAVE_VIEW_OWN,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.SALARY_VIEW_OWN,
    PERMISSIONS.DELIVERABLE_VIEW,
    PERMISSIONS.DELIVERABLE_CREATE,
    PERMISSIONS.DELIVERABLE_PUBLISH,
    PERMISSIONS.DELIVERABLE_APPROVE,
    PERMISSIONS.DELIVERABLE_REQUEST_CHANGES,
    PERMISSIONS.NOTIFICATION_VIEW_OWN,
    PERMISSIONS.NOTIFICATION_MANAGE_PREFERENCES,
  ],
  EMPLOYEE: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW_OWN,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_VIEW_OWN,
    PERMISSIONS.SALARY_VIEW_OWN,
    PERMISSIONS.NOTIFICATION_VIEW_OWN,
    PERMISSIONS.NOTIFICATION_MANAGE_PREFERENCES,
  ],
  ACCOUNTANT: [
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW_OWN,
    PERMISSIONS.ATTENDANCE_VIEW_ALL,
    PERMISSIONS.SALARY_VIEW_OWN,
    PERMISSIONS.SALARY_VIEW_ALL,
    PERMISSIONS.SALARY_CREATE,
    PERMISSIONS.SALARY_UPDATE,
    PERMISSIONS.PAYROLL_CREATE,
    PERMISSIONS.PAYROLL_SUBMIT,
    PERMISSIONS.PAYROLL_APPROVE,
    PERMISSIONS.PAYROLL_LOCK,
    PERMISSIONS.PAYROLL_PAYMENT_RECORD,
    PERMISSIONS.NOTIFICATION_VIEW_OWN,
    PERMISSIONS.NOTIFICATION_MANAGE_PREFERENCES,
  ],
  CLIENT: [
    PERMISSIONS.PROJECT_VIEW,
    PERMISSIONS.TASK_VIEW,
    PERMISSIONS.DELIVERABLE_VIEW,
    PERMISSIONS.DELIVERABLE_APPROVE,
    PERMISSIONS.DELIVERABLE_REQUEST_CHANGES,
    PERMISSIONS.NOTIFICATION_VIEW_OWN,
    PERMISSIONS.NOTIFICATION_MANAGE_PREFERENCES,
  ],
};
